collections:
  facilities_docs:
    output: true
    permalink: /:collection/:name
  finance_docs:
    output: true
    permalink: /:collection/:name
  general_docs:
    output: true
    permalink: /:collection/:name
  hr_docs:
    output: true
    permalink: /:collection/:name
  it_docs:
    output: true
    permalink: /:collection/:name

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: true
