collections:
  facilities:
    output: true
  finance:
    output: true
  general:
    output: true
  hr:
    output: true
  it:
    output: true

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: true
