collections:
  facilities_docs:
    output: true
    permalink: /facilities/:name
  finance_docs:
    output: true
    permalink: /finance/:name
  general_docs:
    output: true
    permalink: /general/:name
  hr_docs:
    output: true
    permalink: /hr/:name
  it_docs:
    output: true
    permalink: /it/:name

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: true
